# Generated by Django 5.1.3 on 2025-03-01 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paiement",
            name="id_transaction",
        ),
        migrations.AddField(
            model_name="abonnement",
            name="prochaine_livraison",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="abonnement",
            name="produits",
            field=models.ManyToManyField(
                help_text="Produits inclus dans l'abonnement",
                related_name="abonnements",
                to="api.produit",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="abonnement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements",
                to="api.abonnement",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="atelier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements",
                to="api.atelier",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="commande",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements",
                to="api.commande",
            ),
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="868630", max_length=6)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("expiration", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
            },
        ),
    ]
