# Generated by Django 5.1.3 on 2025-03-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_paiement_id_transaction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="code",
            field=models.CharField(default="951586", max_length=6),
        ),
    ]
