# Generated by Django 5.1.6 on 2025-03-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_otp_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="is_banned",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="adresse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[("client", "Client"), ("admin", "Administrateur")],
                default="client",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="telephone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
