# Generated by Django 5.1.6 on 2025-03-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_utilisateur_is_banned_alter_utilisateur_adresse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
