# Generated by Django 5.1.6 on 2025-03-02 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_utilisateur_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="prix_reduit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
