# Generated by Django 5.1.6 on 2025-03-02 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_produit_prix_reduit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="prix_reduit",
        ),
    ]
