# Generated by Django 5.1.3 on 2025-03-04 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_adresse_commande_adresse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"role": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "produits",
                    models.ManyToManyField(
                        blank=True, related_name="wishlists", to="api.produit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Liste de souhaits",
                "verbose_name_plural": "Listes de souhaits",
                "unique_together": {("client",)},
            },
        ),
    ]
