# Generated by Django 5.1.3 on 2025-03-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_wishlist"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="admin",
            new_name="auteur",
        ),
        migrations.AddField(
            model_name="article",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="article_covers"),
        ),
    ]
