# Generated by Django 5.1.3 on 2025-03-04 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_rename_admin_article_auteur_article_cover"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reponses",
                to="api.commentaire",
            ),
        ),
    ]
