# Generated by Django 5.1.3 on 2025-03-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_alter_article_auteur_alter_article_titre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commande",
            name="statut",
            field=models.CharField(
                choices=[
                    ("en_attente", "En attente"),
                    ("en_cours", "En cours"),
                    ("expediee", "Expédiée"),
                    ("livree", "Livrée"),
                    ("annulee", "Annulée"),
                ],
                default="en_attente_paiement",
                max_length=20,
            ),
        ),
    ]
