# Generated by Django 5.1.3 on 2025-03-06 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_alter_commande_statut"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="atelier",
            options={},
        ),
        migrations.RemoveField(
            model_name="atelier",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="atelier",
            name="participants",
        ),
        migrations.RemoveField(
            model_name="atelier",
            name="places_disponibles",
        ),
        migrations.RemoveField(
            model_name="atelier",
            name="titre",
        ),
        migrations.AddField(
            model_name="atelier",
            name="duree",
            field=models.IntegerField(default=0, help_text="Durée en minutes"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="atelier",
            name="nom",
            field=models.CharField(default="atelier", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="atelier",
            name="places_totales",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="atelier",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="atelier",
            name="prix",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("inscrit", "Inscrit"),
                            ("present", "Présent"),
                            ("annule", "Annulé"),
                        ],
                        default="inscrit",
                        max_length=20,
                    ),
                ),
                (
                    "atelier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="api.atelier",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("atelier", "utilisateur")},
            },
        ),
    ]
