# Generated by Django 5.1.3 on 2025-03-06 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_atelier_options_remove_atelier_date_creation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paiement",
            name="methode_paiement",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
