# Generated by Django 5.1.3 on 2025-03-11 14:46

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_paiement_date_creation_paiement_methode_paiement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produit",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="realisation",
            name="photos",
        ),
        migrations.RemoveField(
            model_name="service",
            name="photos",
        ),
        migrations.AlterField(
            model_name="otp",
            name="code",
            field=models.CharField(default=api.models.generate_otp_code, max_length=20),
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image au format JPG, JPEG, PNG ou GIF, max 5MB",
                        upload_to="photos/%Y/%m/%d/",
                        validators=[api.models.validate_image],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="api.produit",
                    ),
                ),
                (
                    "realisation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="api.realisation",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="api.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="api.photo"
            ),
        ),
    ]
