# Generated by Django 5.1.3 on 2025-03-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_remove_produit_photos_remove_realisation_photos_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atelier",
            old_name="places_totales",
            new_name="places_disponibles",
        ),
    ]
