# Generated by Django 5.1.3 on 2025-03-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_rename_places_totales_atelier_places_disponibles"),
    ]

    operations = [
        migrations.AddField(
            model_name="atelier",
            name="places_totales",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
