# Generated by Django 5.1.3 on 2025-03-23 21:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_atelier_places_totales"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abonnement",
            options={},
        ),
        migrations.RemoveField(
            model_name="abonnement",
            name="produits",
        ),
        migrations.AlterField(
            model_name="abonnement",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="abonnements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AbonnementProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "abonnement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnement_produits",
                        to="api.abonnement",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.produit"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit d'abonnement",
                "verbose_name_plural": "Produits d'abonnement",
                "unique_together": {("abonnement", "produit")},
            },
        ),
    ]
