# Generated by Django 5.1.3 on 2025-03-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_abonnement_options_remove_abonnement_produits_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="abonnement",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="abonnement",
            name="date_mise_a_jour",
        ),
        migrations.AddField(
            model_name="abonnement",
            name="paiement_statut",
            field=models.CharField(
                choices=[
                    ("non_paye", "Non payé"),
                    ("paye_complet", "Payé en une fois"),
                    ("paye_mensuel", "Payé mensuellement"),
                ],
                default="non_paye",
                max_length=20,
            ),
        ),
    ]
