# Generated by Django 5.1.3 on 2025-03-23 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_abonnement_date_creation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnement",
            name="prochaine_facturation",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="abonnement",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="abonnement",
            name="prix",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
