# Generated by Django 5.1.3 on 2025-03-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_abonnement_prochaine_facturation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnement",
            name="date_creation",
            field=models.DateField(auto_now=True),
        ),
    ]
