# Generated by Django 5.1.3 on 2025-03-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_abonnement_date_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnement",
            name="date_mise_a_jour",
            field=models.DateField(auto_now=True),
        ),
    ]
