# Generated by Django 5.1.3 on 2025-03-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_abonnement_prix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abonnement",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="adresse",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["id"],
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.AlterModelOptions(
            name="categorie",
            options={
                "ordering": ["id"],
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.AlterModelOptions(
            name="commande",
            options={
                "ordering": ["id"],
                "verbose_name": "Commande",
                "verbose_name_plural": "Commandes",
            },
        ),
        migrations.AlterModelOptions(
            name="commentaire",
            options={
                "ordering": ["id"],
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
            },
        ),
        migrations.AlterModelOptions(
            name="devis",
            options={
                "ordering": ["id"],
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
            },
        ),
        migrations.AlterModelOptions(
            name="lignecommande",
            options={
                "ordering": ["id"],
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
            },
        ),
        migrations.AlterModelOptions(
            name="otp",
            options={
                "ordering": ["id"],
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
            },
        ),
        migrations.AlterModelOptions(
            name="panier",
            options={
                "ordering": ["id"],
                "verbose_name": "Panier",
                "verbose_name_plural": "Paniers",
            },
        ),
        migrations.AlterModelOptions(
            name="panierproduit",
            options={
                "ordering": ["id"],
                "verbose_name": "Produit du panier",
                "verbose_name_plural": "Produits du panier",
            },
        ),
        migrations.AlterModelOptions(
            name="parametre",
            options={
                "ordering": ["id"],
                "verbose_name": "Paramètre",
                "verbose_name_plural": "Paramètres",
            },
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={
                "ordering": ["id"],
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
            },
        ),
        migrations.AlterModelOptions(
            name="produit",
            options={
                "ordering": ["id"],
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={
                "ordering": ["id"],
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
            },
        ),
        migrations.AlterModelOptions(
            name="realisation",
            options={
                "ordering": ["id"],
                "verbose_name": "Réalisation",
                "verbose_name_plural": "Réalisations",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["id"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.AlterModelOptions(
            name="utilisateur",
            options={
                "ordering": ["id"],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "ordering": ["id"],
                "verbose_name": "Liste de souhaits",
                "verbose_name_plural": "Listes de souhaits",
            },
        ),
    ]
