# Generated by Django 5.1.3 on 2025-03-25 07:56

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_alter_abonnement_options_alter_adresse_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="devis",
            options={
                "ordering": ["-date_creation"],
                "verbose_name": "Devis",
                "verbose_name_plural": "Devis",
            },
        ),
        migrations.RemoveField(
            model_name="devis",
            name="date_demande",
        ),
        migrations.AddField(
            model_name="devis",
            name="commentaire_admin",
            field=models.TextField(
                blank=True,
                help_text="Commentaire ou justification de l'admin (ex. raison du refus).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Date de création du devis.",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="devis",
            name="date_expiration",
            field=models.DateTimeField(
                blank=True,
                help_text="Date limite pour accepter/refuser le devis.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="date_soumission",
            field=models.DateTimeField(
                blank=True, help_text="Date de soumission à l'admin.", null=True
            ),
        ),
        migrations.AddField(
            model_name="devis",
            name="prix_demande",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix demandé par le client (facultatif).",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="date_mise_a_jour",
            field=models.DateTimeField(
                auto_now=True, help_text="Dernière mise à jour du devis."
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="description",
            field=models.TextField(
                help_text="Description détaillée de la demande du client."
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Indique si le devis est actif ou archivé."
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="prix_propose",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prix proposé par l'admin.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="devis",
            name="statut",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("soumis", "Soumis"),
                    ("en_cours", "En cours"),
                    ("accepte", "Accepté"),
                    ("refuse", "Refusé"),
                    ("expire", "Expiré"),
                ],
                default="brouillon",
                help_text="État actuel du devis.",
                max_length=20,
            ),
        ),
    ]
