# Generated by Django 5.1.3 on 2025-03-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_uploadedimage_remove_article_photos_photo_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produit",
            options={"verbose_name": "Produit", "verbose_name_plural": "Produits"},
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "Promotion", "verbose_name_plural": "Promotions"},
        ),
    ]
