# Generated by Django 5.1.3 on 2025-03-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_alter_produit_options_alter_promotion_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentaire",
            name="ban_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
