# Generated by Django 5.1.3 on 2025-03-25 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_commentaire_ban_reason"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abonnement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="adresse",
            options={},
        ),
        migrations.AlterModelOptions(
            name="article",
            options={"verbose_name": "Article", "verbose_name_plural": "Articles"},
        ),
        migrations.AlterModelOptions(
            name="categorie",
            options={"verbose_name": "Catégorie", "verbose_name_plural": "Catégories"},
        ),
        migrations.AlterModelOptions(
            name="commande",
            options={"verbose_name": "Commande", "verbose_name_plural": "Commandes"},
        ),
        migrations.AlterModelOptions(
            name="lignecommande",
            options={
                "verbose_name": "Ligne de commande",
                "verbose_name_plural": "Lignes de commande",
            },
        ),
        migrations.AlterModelOptions(
            name="otp",
            options={"verbose_name": "OTP", "verbose_name_plural": "OTPs"},
        ),
        migrations.AlterModelOptions(
            name="panier",
            options={"verbose_name": "Panier", "verbose_name_plural": "Paniers"},
        ),
        migrations.AlterModelOptions(
            name="panierproduit",
            options={
                "verbose_name": "Produit du panier",
                "verbose_name_plural": "Produits du panier",
            },
        ),
        migrations.AlterModelOptions(
            name="parametre",
            options={"verbose_name": "Paramètre", "verbose_name_plural": "Paramètres"},
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={},
        ),
        migrations.AlterModelOptions(
            name="photo",
            options={"verbose_name": "Photo", "verbose_name_plural": "Photos"},
        ),
        migrations.AlterModelOptions(
            name="realisation",
            options={
                "verbose_name": "Réalisation",
                "verbose_name_plural": "Réalisations",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Service", "verbose_name_plural": "Services"},
        ),
        migrations.AlterModelOptions(
            name="utilisateur",
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="wishlist",
            options={
                "verbose_name": "Liste de souhaits",
                "verbose_name_plural": "Listes de souhaits",
            },
        ),
    ]
