# Generated by Django 5.1.3 on 2025-03-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_abonnement_options_alter_adresse_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="article",
        ),
    ]
